name: Python App CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest


  docker:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            mohammadrezabazarjani/python-app:latest
            mohammadrezabazarjani/python-app:${{ github.sha }}


  update-infra:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: docker

    runs-on: ubuntu-latest

    steps:

      - name: Checkout infra repo
        run: |
          git clone https://x-access-token:${{ secrets.INFRA_REPO_TOKEN }}@github.com/mohammadrezabazarjani/infra-repo.git

      - name: Update image tag
        run: |
          cd infra-repo

          sed -i "s|image: mohammadrezabazarjani/python-app:.*|image: mohammadrezabazarjani/python-app:${{ github.sha }}|" k8s-manifest/deployment.yml

      - name: Commit and push changes
        run: |
          cd infra-repo

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add k8s-manifest/deployment.yml

          git commit -m "update python-app image to ${{ github.sha }}" || echo "No changes to commit"

          git push origin main